---
title: "Paper Draft"
execute:
  echo: false
  warning: false
format: 
   html:
    embed-resources: true
---

```{r}
library(tidyverse)
library(here)
library(hms)
merged_df <- read_csv(here("Data/merged_output_deployment.csv"))
```

## Introduction

Solar eclipses a rare natural experiment to study changes in animal activity patterns and behaviors in the natural environment. Light dictates many animals circadian rhythm and activity pattern; changes in light levels act as a trigger for a change in behavior such as vocalizing, resting, or foraging. While athroprogenic light pollution at night has been studied and there is research in controlled settings (source) little experimentation has been done on lack of light in natural settings. Previous studies of solar eclipses document a change in vocalization patterns and see a change in the overall 'biophony.' However, there is limited investigation into the species-specific responses to the eclipse and how that contributes to the change in the overall soundcapse. In this study we investigate species-specific changes in vocalization activity through the use of passive acoustic monitoring, AI species identification, and bioacoustic modeling.

Passive acoustic monitoring is an effect method for investigating activity changes through recordings of vocalizations (source). Passive acoustic monitoring is a non-invasive field method in which researchers can identify (auditory) species without disturbing the environment. While an advantage of recorders is that reduce time spent in the field, they have some inherent challenges: (1) the time spent by experts listening the audio recordings and (2) the large volume of data (audio files) produced by autonomous recording. The development of deep learning algorithms that identify species from the audio files, addresses one of the challenges of bioacoustic analysis and makes passive acoustice monitoring a more feasible data collection method. One species identification algorithm is BirdNET, developed by Cornell Lab of Ornithology (source), which breaks audio files into three-second clips to identify a species and provides a 'probability' of its confidence in the prediction. While the use of algorthims like BirdNET drastically reduces the time spent by experts listening to audio, it still does not address the challenge of dealing with the large volume of data, along with introducing new challenges like computing power and how to interpret these confidence scores to extract meaningful insight. Our work attempts to address some of the inherent challenges in using BirdNET for bioacoustic analysis and effectively model a to address a real-world question: what were the species-level response to the 2024 total eclipse? We develop workflow for running BirdNET on a high-performace computing (HPC) cluster and manipulating the output for modeling.

The study area included natural areas around Canton, NY (list them here) where 20 acoustic recorders (AudioMoths; give citation) divided amongst the sites to randomly selected locations (ask Erika/Matt for the specific deployment information). The recording spanned from March 30, 2024 to April 16, 2024 -- several days on either side of the eclipse, which occurred on April 8th with totality in Canton, NY occurring at 3:23:52 PM EDT. (IDK if I should include the recording schedule or not)

*Note:* Add AM schedule and deployment info here and we will add the deployment map as well.

After data collection, the raw audio files were transfered to 

*Note:* in this section talk quickly about workflow and output. Also species list





## Data Exploration







